version: "3"

services:
  pgdb:
    image: postgres:14
    environment:
      POSTGRES_DB: djaerolith
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
      # - ${HOME}/Downloads:/opt/downloads
      # load example:
      # uncomment the ${HOME}/Downloads and replace with your own desired location
      # psql -U postgres -c 'create database djaerolith_prod_backup'
      # psql -U postgres djaerolith_prod_backup < /opt/downloads/backup_20190818-050001.sql
    expose:
      - 5432
    ports:
      - 5437:5432
    networks:
      aeronet:


  app:
    env_file:
      - ./webolith/config/local_config.env
    build: ./webolith
    working_dir: /opt/webolith/djAerolith
    volumes:
      - ./webolith:/opt/webolith:rw
    depends_on:
      - pgdb
      - word_db_server
    links:
      - pgdb
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - aeronet
    labels:
      - "traefik.http.routers.aerolith.rule=Host(`aerolith.localhost`)"
      - "traefik.http.routers.aerolith.entrypoints=web"
      - "traefik.http.services.aerolith.loadbalancer.server.port=8000"
      - traefik.enable=true

  proxy:
    image: "traefik:v2.2"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - aeronet

  word_db_server:
    build:
      context: ./word_db_server
      dockerfile: Dockerfile-dev
    environment:
      WDB_DATA_PATH: /opt/data
      LOG_LEVEL: debug
      # this secret key is the same one as in the local_config.env in
      # webolith. These should match.
      SECRET_KEY: "0gc6=82_ehrw-@fv1a8dqq^6%zuxxu)f^5belgu68cuu*zr&qu"
      DB_MIGRATIONS_PATH: file:///opt/word_db_server/db/migrations
      # These db parameters should match the ones in local_config.env
      DB_CONN_URI: postgres://postgres:pass@pgdb:5432/djaerolith?sslmode=disable
    volumes:
      - ./lexica:/opt/data/lexica
      - ./letterdistributions:/opt/data/letterdistributions
      - ./word_db_server:/opt/word_db_server:rw
    command: sh -c "go run -race cmd/searchserver/*.go"
    networks:
      - aeronet
    labels:
      - "traefik.http.routers.word_db_server.rule=Host(`aerolith.localhost`) && PathPrefix(`/word_db_server/`)"
      - "traefik.http.routers.word_db_server.middlewares=word_db_server-stripprefix"
      - "traefik.http.middlewares.word_db_server-stripprefix.stripprefix.prefixes=/word_db_server/"
      - "traefik.http.routers.word_db_server.entrypoints=web"
      - "traefik.http.services.word_db_server.loadbalancer.server.port=8180"
      - traefik.enable=true

  webpack_webolith:
    build:
      context: ./webolith
      dockerfile: webpack.dockerfile
    volumes:
      - ./webolith:/opt/webolith:rw
      # Install node_modules inside the docker container
      - "/opt/webolith/node_modules"
    working_dir: /opt/webolith
    networks:
      - aeronet
    labels:
      - "traefik.http.routers.webpack_webolith.rule=Host(`aerolith.localhost`) && PathPrefix(`/static/dist`,`/ws`)"
      - "traefik.http.services.webpack_webolith.loadbalancer.server.port=7000"
      - traefik.enable=true

volumes:
  pg-data-volume:
    external: false

networks:
  aeronet:
    driver: bridge
