version: "3"

services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_DB: djaerolith
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
      # - /Users/cesar/Downloads:/opt/downloads
    # load example:
    # create database djaerolith_prod_backup;
    # psql -U postgres djaerolith_prod_backup < /opt/downloads/backup_20190818-050001.sql
    expose:
      - 5432
    ports:
      - 5437:5432
    networks:
      aeronet:

  app:
    env_file:
      - ./webolith/config/local_config.env
    build: ./webolith
    working_dir: /opt/webolith/djAerolith
    volumes:
      - ./webolith:/opt/webolith:rw
    depends_on:
      - pgdb
      - word_db_server
    links:
      - pgdb
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - aeronet
    labels:
      - "traefik.backend=webolith"
      - "traefik.webolith.frontend.rule=Host: vm.aerolith.org"
      - traefik.port=8000
      - traefik.enable=true

  proxy:
    image: traefik:alpine
    command: --web --docker --docker.watch --docker.domain=aerolith.org \
      --logLevel=DEBUG --entryPoints='Name:http Address::80' \
      --defaultEntryPoints='http'
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - aeronet

  word_db_server:
    build:
      context: ./word_db_server
      dockerfile: Dockerfile-dev
    environment:
      LEXICON_PATH: /lexica
      LOG_LEVEL: debug
    volumes:
      - ./lexica:/lexica
      - ./word_db_server:/opt/word_db_server:rw
    command: go run cmd/searchserver/main.go
    networks:
      - aeronet
    labels:
      - "traefik.backend=word_db_server"
      - "traefik.word_db_server.frontend.rule=Host: vm.aerolith.org;PathPrefixStrip: /word_db_server/"
      - traefik.port=8180
      - traefik.enable=true

  webpack_webolith:
    build:
      context: ./webolith
      dockerfile: webpack.dockerfile
    volumes:
      - ./webolith:/opt/webolith:rw
    working_dir: /opt/webolith
    command: yarn dev:wds
    networks:
      - aeronet
    labels:
      - traefik.backend=webpack_webolith
      - "traefik.webpack_webolith.frontend.rule=Host: vm.aerolith.org;PathPrefix: /static/dist/,/sockjs-node/"
      - traefik.port=7000
      - traefik.enable=true

volumes:
  pg-data-volume:
    external: false

networks:
  aeronet:
    driver: bridge
