version: "3"

services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_DB: djaerolith
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5437:5432
    networks:
      aeronet:

  app:
    env_file:
      - ./webolith/config/local_config.env
    build: ./webolith
    working_dir: /opt/webolith/djAerolith
    volumes:
      - ./webolith:/opt/webolith:rw
      - ./lexica/db:/db
    depends_on:
      - pgdb
      - redis
    links:
      - pgdb
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - aeronet
    labels:
      - "traefik.backend=webolith"
      - "traefik.webolith.frontend.rule=Host: vm.aerolith.org"
      - traefik.port=8000
      - traefik.enable=true

  redis:
    image: redis:alpine
    ports:
      - 6384:6379
    networks:
      - aeronet

  proxy:
    image: traefik:alpine
    command: --web --docker --docker.watch --docker.domain=aerolith.org \
      --logLevel=DEBUG --entryPoints='Name:http Address::80' \
      --defaultEntryPoints='http'
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - aeronet

  macondo:
    build:
      context: ./macondo
      dockerfile: Dockerfile-dev
    environment:
      AUTH_KEY: abcdef
    volumes:
      - ./lexica/dawg:/dawgs
      - ./lexica/gaddag:/gaddags
      - ./lexica:/lexica
      - ./macondo:/go/src/github.com/domino14/macondo:rw
    command: go run main.go -dawgpath=/dawgs/
    networks:
      - aeronet
    labels:
      - "traefik.backend=macondo"
      - "traefik.macondo.frontend.rule=Host: vm.aerolith.org;PathPrefixStrip: /macondo/"
      - traefik.port=8088
      - traefik.enable=true

  webpack_webolith:
    build:
      context: ./webolith
      dockerfile: webpack.dockerfile
    volumes:
      - ./webolith:/opt/webolith:rw
    working_dir: /opt/webolith
    command: yarn dev:wds
    networks:
      - aeronet
    labels:
      - traefik.backend=webpack_webolith
      - "traefik.webpack_webolith.frontend.rule=Host: vm.aerolith.org;PathPrefix: /static/dist/,/sockjs-node/"
      - traefik.port=7000
      - traefik.enable=true

  crosswords:
    build: ./liwords
    environment:
      # Must match Django secret key. See setup.sh, where that is set.
      # On prod obviously this will be handled differently.
      DJANGO_SECRET_KEY: 0gc6=82_ehrw-@fv1a8dqq^6%zuxxu)f^5belgu68cuu*zr&qu
    working_dir: /opt/liwords/liwords_ex
    volumes:
      - ./liwords:/opt/liwords:rw
    depends_on:
      - pgdb
    links:
      - pgdb
    command: mix phx.server
    networks:
      - aeronet
    labels:
      - "traefik.backend=crosswords"
      - "traefik.crosswords.frontend.rule=Host: vm.aerolith.org;PathPrefix: /crosswords"
      - traefik.port=4000
      - traefik.enable=true

  webpack_crosswords:
    build:
      context: ./liwords
      dockerfile: webpack.dockerfile
    volumes:
      - ./liwords:/opt/liwords:rw
    working_dir: /opt/liwords
    command: yarn dev:wds
    networks:
      - aeronet
    labels:
      - traefik.backend=webpack_webolith
      - "traefik.webpack_webolith.frontend.rule=Host: vm.aerolith.org;PathPrefix: /crosswords/static/dist/,/sockjs-node/"
      - traefik.port=7000
      - traefik.enable=true


volumes:
  pg-data-volume:
    external: false

networks:
  aeronet:
    driver: bridge
