apiVersion: v1
data:
  AWS_SECRET_ACCESS_KEY: ''
  DJANGO_SECRET_KEY: ''
  MAILGUN_PW: ''
  PGSQL_HOST: ''
  PGSQL_PASSWORD: ''
  RECAPTCHA_PRIVATE_KEY: ''
  SOCIAL_AUTH_FACEBOOK_SECRET: ''
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ''
kind: Secret
metadata:
  name: webolith-secrets
type: Opaque
