kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: macondo-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webolith
        component: macondo
    spec:
      containers:
      - name: macondo-container
        image: domino14/macondo:{{ MACONDO_BUILD_NUM }}
        env:
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: macondo-secrets
                key: AUTH_KEY
        volumeMounts:
        - mountPath: /dawgs
          name: dawg-data

      volumes:
      - name: dawg-data
        hostPath:
          # Change this path to relevant dawg path.
          path: {{ DAWG_PATH }}

      restartPolicy: Always
