apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webolith-ingress
  annotations:
    nginx.org/websocket-services: "webolith"
    nginx.org/rewrites: "serviceName=macondo rewrite=/"
spec:
  backend:
    # The default backend.
    serviceName: webolith
    servicePort: 8000
  tls:
  - hosts:
    - {{ HOST_NAME }}
    secretName: webolith-crt-secret
  rules:
  - host: {{ HOST_NAME }}
    http:
      paths:
      - path: /static
        backend:
          serviceName: nginx-static-svc
          servicePort: 80
      - path: /macondo/
        backend:
          serviceName: macondo
          servicePort: 8088
