kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: word-db-server-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webolith
        component: word-db-server
    spec:
      containers:
      - name: word-db-server-container
        image: domino14/word_db_server:{{ WDB_SERVER_BUILD_NUM }}
        volumeMounts:
        - mountPath: /lexica
          name: lexica-vol
        readinessProbe:
          exec:
            command:
            - cat
            - /go/src/github.com/domino14/word_db_server/README.md
          successThreshold: 1
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 5

        lifecycle:
          preStop:
            exec:
              # A hack to try to get 0% downtime during deploys. This should
              # help ensure k8s eventually stops giving this node traffic.
              command: ["sh", "-c", "rm /go/src/github.com/domino14/word_db_server/README.md && sleep 20"]

        env:
          - name: LEXICON_PATH
            value: /lexica

      volumes:
      - name: lexica-vol
        hostPath:
          # Change this path to relevant lexicon path.
          path: {{ HOST_LEXICON_PATH }}

      restartPolicy: Always
